export const fs: {
  readonly exists: typeof fso.exists.__promisify__
  readonly readdir: typeof fso.promises.readdir
  readonly readDir: typeof fso.promises.readdir
  readonly readFile: typeof fso.promises.readFile
  readonly readfile: typeof fso.promises.readFile
  readonly rmdir: typeof fso.promises.rmdir
  readonly rmDir: typeof fso.promises.rmdir
  readonly watch: typeof fso.watch
  readonly access: typeof fso.promises.access
  readonly copyFile: typeof fso.promises.copyFile
  readonly open: typeof fso.promises.open
  readonly rename: typeof fso.promises.rename
  readonly truncate: typeof fso.promises.truncate
  readonly rm: typeof fso.promises.rm
  readonly mkdir: typeof fso.promises.mkdir
  readonly readlink: typeof fso.promises.readlink
  readonly symlink: typeof fso.promises.symlink
  readonly lstat: typeof fso.promises.lstat
  readonly stat: typeof fso.promises.stat
  readonly statfs: typeof fso.promises.statfs
  readonly link: typeof fso.promises.link
  readonly unlink: typeof fso.promises.unlink
  readonly chmod: typeof fso.promises.chmod
  readonly lchmod: typeof fso.promises.lchmod
  readonly lchown: typeof fso.promises.lchown
  readonly lutimes: typeof fso.promises.lutimes
  readonly chown: typeof fso.promises.chown
  readonly utimes: typeof fso.promises.utimes
  readonly realpath: typeof fso.promises.realpath
  readonly mkdtemp: typeof fso.promises.mkdtemp
  readonly mkdtempDisposable: typeof fso.promises.mkdtempDisposable
  readonly writeFile: typeof fso.promises.writeFile
  readonly appendFile: typeof fso.promises.appendFile
  readonly opendir: typeof fso.promises.opendir
  readonly cp: typeof fso.promises.cp
  readonly glob: typeof fso.promises.glob
  readonly constants: typeof fso.constants
  readonly renameSync: typeof fso.renameSync
  readonly truncateSync: typeof fso.truncateSync
  readonly ftruncate: typeof fso.ftruncate
  readonly ftruncateSync: typeof fso.ftruncateSync
  readonly chownSync: typeof fso.chownSync
  readonly fchown: typeof fso.fchown
  readonly fchownSync: typeof fso.fchownSync
  readonly lchownSync: typeof fso.lchownSync
  readonly lutimesSync: typeof fso.lutimesSync
  readonly chmodSync: typeof fso.chmodSync
  readonly fchmod: typeof fso.fchmod
  readonly fchmodSync: typeof fso.fchmodSync
  readonly lchmodSync: typeof fso.lchmodSync
  readonly fstat: typeof fso.fstat
  readonly fstatSync: typeof fso.fstatSync
  readonly statfsSync: typeof fso.statfsSync
  readonly linkSync: typeof fso.linkSync
  readonly symlinkSync: typeof fso.symlinkSync
  readonly readlinkSync: typeof fso.readlinkSync
  readonly realpathSync: typeof fso.realpathSync
  readonly unlinkSync: typeof fso.unlinkSync
  readonly rmdirSync: typeof fso.rmdirSync
  readonly rmSync: typeof fso.rmSync
  readonly mkdirSync: typeof fso.mkdirSync
  readonly mkdtempSync: typeof fso.mkdtempSync
  readonly mkdtempDisposableSync: typeof fso.mkdtempDisposableSync
  readonly readdirSync: typeof fso.readdirSync
  readonly close: typeof fso.close
  readonly closeSync: typeof fso.closeSync
  readonly openSync: typeof fso.openSync
  readonly utimesSync: typeof fso.utimesSync
  readonly futimes: typeof fso.futimes
  readonly futimesSync: typeof fso.futimesSync
  readonly fsync: typeof fso.fsync
  readonly fsyncSync: typeof fso.fsyncSync
  readonly write: typeof fso.write
  readonly writeSync: typeof fso.writeSync
  readonly read: typeof fso.read
  readonly readSync: typeof fso.readSync
  readonly readFileSync: typeof fso.readFileSync
  readonly writeFileSync: typeof fso.writeFileSync
  readonly appendFileSync: typeof fso.appendFileSync
  readonly watchFile: typeof fso.watchFile
  readonly unwatchFile: typeof fso.unwatchFile
  readonly existsSync: typeof fso.existsSync
  readonly accessSync: typeof fso.accessSync
  readonly createReadStream: typeof fso.createReadStream
  readonly createWriteStream: typeof fso.createWriteStream
  readonly fdatasync: typeof fso.fdatasync
  readonly fdatasyncSync: typeof fso.fdatasyncSync
  readonly copyFileSync: typeof fso.copyFileSync
  readonly writev: typeof fso.writev
  readonly writevSync: typeof fso.writevSync
  readonly readv: typeof fso.readv
  readonly readvSync: typeof fso.readvSync
  readonly openAsBlob: typeof fso.openAsBlob
  readonly opendirSync: typeof fso.opendirSync
  readonly cpSync: typeof fso.cpSync
  readonly globSync: typeof fso.globSync
  readonly promises: typeof fso.promises
  readonly Stats: typeof fso.Stats
  readonly StatsFs: typeof fso.StatsFs
  readonly Dirent: typeof fso.Dirent
  readonly Dir: typeof fso.Dir
  readonly ReadStream: typeof fso.ReadStream
  readonly Utf8Stream: typeof fso.Utf8Stream
  readonly WriteStream: typeof fso.WriteStream
  readonly statSync: fso.StatSyncFn
  readonly lstatSync: fso.StatSyncFn
}
import fso from 'node:fs'
